### ISSUE TITLE
Commands not working outside of chat

### ISSUE THREAD

**Issue by BitterMilk** [GoldenShad0w/ItemSave#1]
Seems like commands don't work in .yml files or command blocks

**Comment by GoldenShad0w** [comment]
you're right. I'll try to fix that as soon as possible

**Comment by GoldenShad0w** [comment]
@BitterMilk should be fixed now! You can download the new version in the releases tab or on the spigot page (https://www.spigotmc.org/resources/itemsave-easily-save-and-load-custom-items-1-18-1-19-4.109598/)
